import { chromium } from '/Users/aeriek/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await (await browser.newContext()).newPage();
const errs = [];
page.on('pageerror', (e) => errs.push(e.message.slice(0,120)));
await page.goto('http://localhost:5231/');
await page.waitForSelector('#login-user', { state: 'visible', timeout: 15000 });
const vis = (sel) => page.isVisible(sel);
const s1 = { user: await vis('#login-user'), charname: await vis('#login-charname'), invite: await vis('#login-invite') };
await page.click('#login-toggle');
const s2 = { charname: await vis('#login-charname'), invite: await vis('#login-invite'), btn: await page.textContent('#login-submit') };
await page.click('#login-toggle');
const s3 = { charname: await vis('#login-charname') };
// quick view via roster: log in once so a card is written, reload, expect roster
await page.fill('#login-user', 'perf12_probe');
await page.fill('#login-pass', 'probe-owl-9127');
await page.click('#login-submit');
await page.waitForFunction(() => window.dcGame && window.dcGame.connStatus === 'ingame', null, { timeout: 30000 });
await page.evaluate(() => localStorage.removeItem('arx.token'));
await page.reload();
await page.waitForSelector('#login', { state: 'visible', timeout: 15000 });
await page.waitForTimeout(800);
const s4 = { roster: await vis('#login-roster'), user: await vis('#login-user') };
const rosterCard = await page.evaluate(() => document.querySelector('#login-roster')?.children.length ?? 0);
console.log('signin:', JSON.stringify(s1), 'register:', JSON.stringify(s2), 'back:', JSON.stringify(s3));
console.log('after-card reload:', JSON.stringify(s4), 'cards:', rosterCard, 'errors:', errs.length, errs[0] ?? '');
const ok = s1.user && !s1.charname && s2.charname && s2.invite && !s3.charname && s4.roster && !s4.user && rosterCard > 0 && errs.length === 0;
console.log(ok ? 'LOGIN VIEWS PASS' : 'LOGIN VIEWS FAIL');
await browser.close();
process.exit(ok ? 0 : 1);
