import type { SkillId, StationType } from '@devcraft/shared';

export interface RecipeDef {
  id: string;
  name: string;
  skill: SkillId;
  levelReq: number;
  xp: number;
  /** Required adjacent station; null = craftable anywhere. */
  station: StationType | null;
  inputs: Array<{ item: string; qty: number }>;
  output: { item: string; qty: number };
  /** Ticks per craft. */
  ticks: number;
  /** Cooking-style failure chance at the required level (fades with levels). */
  burnChance?: number;
  burnResult?: string;
}

const defs: RecipeDef[] = [
  // ------------------------------------------------ cooking (fire)
  {
    id: 'cook_trout',
    name: 'Trout',
    skill: 'cooking',
    levelReq: 1,
    xp: 30,
    station: 'fire',
    inputs: [{ item: 'raw_trout', qty: 1 }],
    output: { item: 'trout', qty: 1 },
    ticks: 30,
    burnChance: 0.3,
    burnResult: 'burnt_food',
  },
  {
    id: 'cook_chicken',
    name: 'Cooked chicken',
    skill: 'cooking',
    levelReq: 1,
    xp: 25,
    station: 'fire',
    inputs: [{ item: 'raw_chicken', qty: 1 }],
    output: { item: 'cooked_chicken', qty: 1 },
    ticks: 30,
    burnChance: 0.25,
    burnResult: 'burnt_food',
  },
  {
    id: 'cook_beef',
    name: 'Cooked beef',
    skill: 'cooking',
    levelReq: 1,
    xp: 28,
    station: 'fire',
    inputs: [{ item: 'raw_beef', qty: 1 }],
    output: { item: 'cooked_beef', qty: 1 },
    ticks: 30,
    burnChance: 0.25,
    burnResult: 'burnt_food',
  },

  // ------------------------------------------------ smithing
  {
    id: 'smelt_bronze',
    name: 'Bronze bar',
    skill: 'smithing',
    levelReq: 1,
    xp: 25,
    station: 'furnace',
    // The classic alloy: one copper, one tin.
    inputs: [
      { item: 'copper_ore', qty: 1 },
      { item: 'tin_ore', qty: 1 },
    ],
    output: { item: 'bronze_bar', qty: 1 },
    ticks: 40,
  },
  {
    id: 'smelt_iron',
    name: 'Iron bar',
    skill: 'smithing',
    levelReq: 15,
    xp: 50,
    station: 'furnace',
    inputs: [{ item: 'iron_ore', qty: 1 }],
    output: { item: 'iron_bar', qty: 1 },
    ticks: 50,
  },
  {
    id: 'smelt_steel',
    name: 'Steel bar',
    skill: 'smithing',
    levelReq: 30,
    xp: 80,
    station: 'furnace',
    inputs: [
      { item: 'iron_ore', qty: 1 },
      { item: 'coal', qty: 2 },
    ],
    output: { item: 'steel_bar', qty: 1 },
    ticks: 60,
  },
  {
    id: 'smelt_gold',
    name: 'Gold bar',
    skill: 'smithing',
    levelReq: 40,
    xp: 90,
    station: 'furnace',
    inputs: [{ item: 'gold_ore', qty: 1 }],
    output: { item: 'gold_bar', qty: 1 },
    ticks: 50,
  },
  {
    id: 'smith_bronze_sword',
    name: 'Bronze sword',
    skill: 'smithing',
    levelReq: 4,
    xp: 60,
    station: 'anvil',
    inputs: [{ item: 'bronze_bar', qty: 2 }],
    output: { item: 'bronze_sword', qty: 1 },
    ticks: 60,
  },
  {
    id: 'smith_iron_sword',
    name: 'Iron sword',
    skill: 'smithing',
    levelReq: 18,
    xp: 130,
    station: 'anvil',
    inputs: [{ item: 'iron_bar', qty: 2 }],
    output: { item: 'iron_sword', qty: 1 },
    ticks: 70,
  },
  {
    id: 'smith_steel_sword',
    name: 'Steel sword',
    skill: 'smithing',
    levelReq: 33,
    xp: 250,
    station: 'anvil',
    inputs: [{ item: 'steel_bar', qty: 2 }],
    output: { item: 'steel_sword', qty: 1 },
    ticks: 80,
  },
  {
    id: 'smith_gold_ring',
    name: 'Gold ring',
    skill: 'smithing',
    levelReq: 42,
    xp: 160,
    station: 'anvil',
    inputs: [{ item: 'gold_bar', qty: 1 }],
    output: { item: 'gold_ring', qty: 1 },
    ticks: 60,
  },

  // ------------------------------------------------ crafting
  {
    id: 'craft_leather',
    name: 'Leather',
    skill: 'crafting',
    levelReq: 1,
    xp: 20,
    station: 'workbench',
    inputs: [{ item: 'cowhide', qty: 1 }],
    output: { item: 'leather', qty: 1 },
    ticks: 30,
  },
  {
    id: 'craft_leather_body',
    name: 'Leather body',
    skill: 'crafting',
    levelReq: 8,
    xp: 75,
    station: 'workbench',
    inputs: [{ item: 'leather', qty: 3 }],
    output: { item: 'leather_body', qty: 1 },
    ticks: 60,
  },
  {
    id: 'fletch_arrows',
    name: 'Arrows (x10)',
    skill: 'crafting',
    levelReq: 1,
    xp: 25,
    station: null,
    inputs: [
      { item: 'log', qty: 1 },
      { item: 'feather', qty: 5 },
    ],
    output: { item: 'arrow', qty: 10 },
    ticks: 40,
  },
  {
    id: 'fletch_oak_shortbow',
    name: 'Oak shortbow',
    skill: 'crafting',
    levelReq: 10,
    xp: 80,
    station: null,
    inputs: [{ item: 'oak_log', qty: 2 }],
    output: { item: 'oak_shortbow', qty: 1 },
    ticks: 60,
  },

  // Passive gear — craftable builds, not just lucky drops.
  {
    id: 'smith_spiked_buckler',
    name: 'Spiked buckler',
    skill: 'smithing',
    levelReq: 18,
    xp: 120,
    station: 'anvil',
    inputs: [{ item: 'iron_bar', qty: 2 }],
    output: { item: 'spiked_buckler', qty: 1 },
    ticks: 70,
  },
  {
    id: 'craft_wolf_pelt_cloak',
    name: 'Wolf-pelt cloak',
    skill: 'crafting',
    levelReq: 14,
    xp: 110,
    station: 'workbench',
    inputs: [
      { item: 'wolf_fur', qty: 3 },
      { item: 'leather', qty: 1 },
    ],
    output: { item: 'wolf_pelt_cloak', qty: 1 },
    ticks: 70,
  },
  {
    id: 'craft_frost_quiver',
    name: 'Frost quiver',
    skill: 'crafting',
    levelReq: 20,
    xp: 140,
    station: 'workbench',
    inputs: [
      { item: 'leather', qty: 2 },
      { item: 'gold_bar', qty: 1 },
    ],
    output: { item: 'frost_quiver', qty: 1 },
    ticks: 80,
  },
  {
    id: 'craft_cape_traveler',
    name: "Traveler's cape",
    skill: 'crafting',
    levelReq: 8,
    xp: 80,
    station: 'workbench',
    inputs: [
      { item: 'leather', qty: 2 },
      { item: 'wolf_fur', qty: 1 },
    ],
    output: { item: 'cape_traveler', qty: 1 },
    ticks: 60,
  },
  {
    id: 'craft_cape_ragged',
    name: 'Ragged cloak',
    skill: 'crafting',
    levelReq: 2,
    xp: 30,
    station: 'workbench',
    inputs: [{ item: 'leather', qty: 2 }],
    output: { item: 'cape_ragged', qty: 1 },
    ticks: 40,
  },
  {
    id: 'craft_cape_huntsman',
    name: "Huntsman's drape",
    skill: 'crafting',
    levelReq: 20,
    xp: 150,
    station: 'workbench',
    inputs: [
      { item: 'leather', qty: 3 },
      { item: 'wolf_fur', qty: 2 },
    ],
    output: { item: 'cape_huntsman', qty: 1 },
    ticks: 80,
  },
  {
    id: 'craft_cape_gilded',
    name: 'Gilded cape',
    skill: 'crafting',
    levelReq: 26,
    xp: 210,
    station: 'workbench',
    inputs: [
      { item: 'leather', qty: 2 },
      { item: 'gold_bar', qty: 2 },
    ],
    output: { item: 'cape_gilded', qty: 1 },
    ticks: 90,
  },

  // ------------------------------------------------ homestead cooking
  {
    id: 'mill_flour',
    name: 'Flour',
    skill: 'cooking',
    levelReq: 5,
    xp: 15,
    station: 'workbench',
    inputs: [{ item: 'wheat', qty: 2 }],
    output: { item: 'flour', qty: 1 },
    ticks: 25,
  },
  {
    id: 'cook_bread',
    name: 'Bread',
    skill: 'cooking',
    levelReq: 8,
    xp: 40,
    station: 'fire',
    inputs: [{ item: 'flour', qty: 1 }],
    output: { item: 'bread', qty: 1 },
    ticks: 35,
    burnChance: 0.25,
    burnResult: 'burnt_food',
  },
  {
    id: 'cook_fried_egg',
    name: 'Fried egg',
    skill: 'cooking',
    levelReq: 1,
    xp: 20,
    station: 'fire',
    inputs: [{ item: 'egg', qty: 1 }],
    output: { item: 'fried_egg', qty: 1 },
    ticks: 25,
    burnChance: 0.25,
    burnResult: 'burnt_food',
  },
  {
    id: 'cook_hearty_stew',
    name: 'Hearty stew',
    skill: 'cooking',
    levelReq: 12,
    xp: 65,
    station: 'fire',
    inputs: [
      { item: 'carrot', qty: 1 },
      { item: 'raw_beef', qty: 1 },
    ],
    output: { item: 'hearty_stew', qty: 1 },
    ticks: 45,
    burnChance: 0.2,
    burnResult: 'burnt_food',
  },
  {
    id: 'cook_cake',
    name: 'Cake',
    skill: 'cooking',
    levelReq: 15,
    xp: 90,
    station: 'fire',
    inputs: [
      { item: 'flour', qty: 1 },
      { item: 'egg', qty: 1 },
      { item: 'milk', qty: 1 },
    ],
    output: { item: 'cake', qty: 1 },
    ticks: 55,
    burnChance: 0.2,
    burnResult: 'burnt_food',
  },

  // ------------------------------------------------ homestead crafting
  {
    id: 'craft_twine',
    name: 'Twine',
    skill: 'crafting',
    levelReq: 1,
    xp: 12,
    station: null,
    inputs: [{ item: 'plant_fibre', qty: 2 }],
    output: { item: 'twine', qty: 1 },
    ticks: 20,
  },
  {
    id: 'craft_cloth',
    name: 'Cloth',
    skill: 'crafting',
    levelReq: 10,
    xp: 40,
    station: 'workbench',
    inputs: [{ item: 'cotton', qty: 2 }],
    output: { item: 'cloth', qty: 1 },
    ticks: 35,
  },
  {
    id: 'craft_flower_crown',
    name: 'Flower crown',
    skill: 'crafting',
    levelReq: 5,
    xp: 35,
    station: 'workbench',
    inputs: [
      { item: 'sunflower', qty: 3 },
      { item: 'twine', qty: 1 },
    ],
    output: { item: 'flower_crown', qty: 1 },
    ticks: 40,
  },
  {
    id: 'smith_watering_can',
    name: 'Watering can',
    skill: 'smithing',
    levelReq: 5,
    xp: 40,
    station: 'anvil',
    inputs: [{ item: 'bronze_bar', qty: 1 }],
    output: { item: 'watering_can', qty: 1 },
    ticks: 40,
  },

  // ------------------------------------------------ herbalism (alembic)
  {
    id: 'brew_healing_tincture',
    name: 'Healing tincture',
    skill: 'herbalism',
    levelReq: 1,
    xp: 30,
    station: 'alembic',
    inputs: [
      { item: 'sagewort', qty: 1 },
      { item: 'berries', qty: 1 },
    ],
    output: { item: 'healing_tincture', qty: 1 },
    ticks: 35,
  },
  {
    id: 'brew_gatherers_brew',
    name: 'Gatherer\'s brew',
    skill: 'herbalism',
    levelReq: 5,
    xp: 45,
    station: 'alembic',
    inputs: [
      { item: 'sagewort', qty: 1 },
      { item: 'carrot', qty: 1 },
    ],
    output: { item: 'gatherers_brew', qty: 1 },
    ticks: 40,
  },
  {
    id: 'brew_swiftness_tonic',
    name: 'Swiftness tonic',
    skill: 'herbalism',
    levelReq: 10,
    xp: 60,
    station: 'alembic',
    inputs: [
      { item: 'sunflower', qty: 1 },
      { item: 'sagewort', qty: 1 },
    ],
    output: { item: 'swiftness_tonic', qty: 1 },
    ticks: 45,
  },
  {
    id: 'brew_ironbark_tonic',
    name: 'Ironbark tonic',
    skill: 'herbalism',
    levelReq: 15,
    xp: 80,
    station: 'alembic',
    inputs: [
      { item: 'moonbell', qty: 1 },
      { item: 'milk', qty: 1 },
    ],
    output: { item: 'ironbark_tonic', qty: 1 },
    ticks: 50,
  },
  {
    id: 'brew_mending_salve',
    name: 'Mending salve',
    skill: 'herbalism',
    levelReq: 25,
    xp: 120,
    station: 'alembic',
    inputs: [
      { item: 'moonbell', qty: 2 },
      { item: 'milk', qty: 1 },
    ],
    output: { item: 'mending_salve', qty: 1 },
    ticks: 60,
  },
];

export const RECIPES: ReadonlyMap<string, RecipeDef> = new Map(defs.map((d) => [d.id, d]));

export function recipesForStation(station: StationType | null): RecipeDef[] {
  return [...RECIPES.values()].filter((r) => r.station === station);
}
