import { compileEquipment } from './compile.js';
import type { AffixPoolEntry, EquipmentDef } from './types.js';

/**
 * The starter equipment roster — enough pieces per slot and class to
 * verify the whole system end-to-end (rolls, requirements, class mods,
 * crafting bias, drop-only chases). The big 20-per-slot content pass
 * authors more of THESE records; defs are JSON-safe and round-trip
 * through equipment/serialize.ts.
 */

// Class-flavored affix pools. Local shorthand only — a JSON authoring
// tool would inline these; the serialized form always carries the pool.
const CLOTH_POOL: AffixPoolEntry[] = [
  { stat: 'magic', w: 3 },
  { stat: 'vitality' },
  { stat: 'herbalism' },
  { stat: 'regen' },
];
const LEATHER_POOL: AffixPoolEntry[] = [
  { stat: 'archery', w: 3 },
  { stat: 'sneak' },
  { stat: 'foraging' },
  { stat: 'maxHp' },
];
const PLATE_POOL: AffixPoolEntry[] = [
  { stat: 'melee', w: 2 },
  { stat: 'defence', w: 2 },
  { stat: 'vitality' },
  { stat: 'maxHp' },
];

export const EQUIPMENT_DEFS: EquipmentDef[] = [
  // ------------------------------------------------ body
  {
    id: 'apprentice_robe',
    name: 'Apprentice robe',
    slot: 'body',
    armorClass: 'cloth',
    levelReq: { skill: 'magic', level: 4 },
    armor: 2,
    affixPool: CLOTH_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 6,
      xp: 55,
      station: 'workbench',
      ticks: 50,
      inputs: [
        { item: 'cloth', qty: 2 },
        { item: 'twine', qty: 1 },
      ],
    },
    value: 60,
    color: '#5a6ea0',
    code: 'Ar',
    desc: 'Hems inked with first-year glyphs, most spelled correctly.',
  },
  {
    id: 'emberweave_robe',
    name: 'Emberweave robe',
    slot: 'body',
    armorClass: 'cloth',
    levelReq: { skill: 'magic', level: 24 },
    armor: 3,
    affixPool: [...CLOTH_POOL, { stat: 'cooking' }],
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 30,
      xp: 240,
      station: 'workbench',
      ticks: 90,
      inputs: [
        { item: 'cloth', qty: 3 },
        { item: 'wolf_fur', qty: 2 },
        { item: 'gold_bar', qty: 1 },
      ],
    },
    value: 420,
    color: '#c4553d',
    code: 'Er',
    desc: 'Warm as a hearth and twice as opinionated.',
  },
  {
    id: 'leather_body',
    name: 'Leather body',
    slot: 'body',
    armorClass: 'leather',
    levelReq: { skill: 'defence', level: 5 },
    armor: 4,
    affixPool: LEATHER_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 8,
      xp: 75,
      station: 'workbench',
      ticks: 60,
      inputs: [{ item: 'leather', qty: 3 }],
    },
    value: 40,
    color: '#b08a5c',
    code: 'LB',
    desc: "Boiled leather that turns a blade's first bite.",
  },
  {
    id: 'huntsman_jerkin',
    name: "Huntsman's jerkin",
    slot: 'body',
    armorClass: 'leather',
    levelReq: { skill: 'defence', level: 12 },
    armor: 5,
    affixPool: [...LEATHER_POOL, { stat: 'woodcutting' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 16,
      xp: 130,
      station: 'workbench',
      ticks: 70,
      inputs: [
        { item: 'leather', qty: 3 },
        { item: 'wolf_fur', qty: 1 },
      ],
    },
    value: 260,
    color: '#3f6b3a',
    code: 'Hj',
    desc: 'Studded green leather that moves quiet and takes a hit.',
  },
  {
    id: 'iron_platebody',
    name: 'Iron platebody',
    slot: 'body',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 10 },
    armor: 6,
    affixPool: PLATE_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'smithing',
      levelReq: 20,
      xp: 180,
      station: 'anvil',
      ticks: 80,
      inputs: [{ item: 'iron_bar', qty: 3 }],
    },
    value: 300,
    color: '#8d9299',
    code: 'Ip',
    desc: 'A chest of honest iron. Arrows write it angry letters.',
  },
  {
    id: 'steel_platebody',
    name: 'Steel platebody',
    slot: 'body',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 30 },
    armor: 9,
    affixPool: [...PLATE_POOL, { stat: 'smithing' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'smithing',
      levelReq: 34,
      xp: 300,
      station: 'anvil',
      ticks: 95,
      inputs: [{ item: 'steel_bar', qty: 3 }],
    },
    value: 700,
    color: '#b8bec8',
    code: 'Sp',
    desc: 'Anvil-song in full chorus, gold-chased at the collar.',
  },

  // ------------------------------------------------ head
  {
    id: 'flower_crown',
    name: 'Flower crown',
    slot: 'head',
    armorClass: 'cloth',
    armor: 0,
    affixPool: [{ stat: 'farming', w: 2 }, { stat: 'foraging' }, { stat: 'herbalism' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 5,
      xp: 35,
      station: 'workbench',
      ticks: 40,
      inputs: [
        { item: 'sunflower', qty: 3 },
        { item: 'twine', qty: 1 },
      ],
    },
    value: 35,
    color: '#e8c04c',
    code: 'Fc',
    desc: 'Sunflowers woven with twine. Armor value: joy.',
  },
  {
    id: 'iron_helm',
    name: 'Iron helm',
    slot: 'head',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 8 },
    armor: 3,
    affixPool: PLATE_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'smithing',
      levelReq: 12,
      xp: 100,
      station: 'anvil',
      ticks: 60,
      inputs: [{ item: 'iron_bar', qty: 2 }],
    },
    value: 120,
    color: '#8d9299',
    code: 'Ih',
    desc: 'A dented dome that has already saved one skull. Yours next.',
  },
  {
    id: 'leather_hood',
    name: 'Leather hood',
    slot: 'head',
    armorClass: 'leather',
    levelReq: { skill: 'defence', level: 5 },
    armor: 2,
    affixPool: LEATHER_POOL,
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 6,
      xp: 50,
      station: 'workbench',
      ticks: 45,
      inputs: [{ item: 'leather', qty: 2 }],
    },
    value: 90,
    color: '#8a6a45',
    code: 'Lh',
    desc: 'Keeps the rain off and your face out of the story.',
  },
  {
    id: 'wolfhide_hood',
    name: 'Wolfhide hood',
    slot: 'head',
    armorClass: 'leather',
    levelReq: { skill: 'archery', level: 15 },
    armor: 3,
    affixPool: [{ stat: 'archery', w: 3 }, { stat: 'sneak', w: 2 }, { stat: 'maxHp' }],
    acquisition: { drop: true },
    value: 320,
    color: '#6a6f7d',
    code: 'Wh',
    desc: 'The pack still hunts — you just walk at the front now.',
  },
  {
    id: 'runecloth_cowl',
    name: 'Runecloth cowl',
    slot: 'head',
    armorClass: 'cloth',
    levelReq: { skill: 'magic', level: 20 },
    armor: 2,
    affixPool: [{ stat: 'magic', w: 3 }, { stat: 'herbalism' }, { stat: 'regen' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 22,
      xp: 190,
      station: 'workbench',
      ticks: 80,
      inputs: [
        { item: 'cloth', qty: 3 },
        { item: 'moonbell', qty: 2 },
      ],
    },
    value: 380,
    color: '#7a5ac4',
    code: 'Rc',
    desc: 'Only a master weaver can set runes in thread. Prove it.',
  },
  {
    id: 'steel_greathelm',
    name: 'Steel greathelm',
    slot: 'head',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 32 },
    armor: 5,
    affixPool: [...PLATE_POOL, { stat: 'mining' }],
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'smithing',
      levelReq: 36,
      xp: 280,
      station: 'anvil',
      ticks: 90,
      inputs: [
        { item: 'steel_bar', qty: 2 },
        { item: 'iron_bar', qty: 1 },
      ],
    },
    value: 520,
    color: '#b8bec8',
    code: 'Gh',
    desc: 'The world through a slit: smaller, simpler, survivable.',
  },
  {
    id: 'horned_raider_helm',
    name: 'Horned raider helm',
    slot: 'head',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 18 },
    armor: 4,
    affixPool: [{ stat: 'melee', w: 3 }, { stat: 'vitality' }, { stat: 'maxHp' }],
    acquisition: { drop: true },
    value: 340,
    color: '#7d6a52',
    code: 'Rh',
    desc: 'Impractical, intimidating, and absolutely worth it.',
  },

  // ------------------------------------------------ legs
  {
    id: 'woven_trousers',
    name: 'Woven trousers',
    slot: 'legs',
    armorClass: 'cloth',
    armor: 1,
    affixPool: CLOTH_POOL,
    acquisition: { craft: true, shop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 3,
      xp: 30,
      station: 'workbench',
      ticks: 40,
      inputs: [
        { item: 'cloth', qty: 1 },
        { item: 'twine', qty: 1 },
      ],
    },
    value: 40,
    color: '#8f9ed6',
    code: 'Wt',
    desc: 'Soft, warm, and no trouble at all to run in.',
  },
  {
    id: 'leather_chaps',
    name: 'Leather chaps',
    slot: 'legs',
    armorClass: 'leather',
    levelReq: { skill: 'defence', level: 8 },
    armor: 3,
    affixPool: LEATHER_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 10,
      xp: 70,
      station: 'workbench',
      ticks: 55,
      inputs: [{ item: 'leather', qty: 2 }],
    },
    value: 150,
    color: '#b08a5c',
    code: 'Lc',
    desc: 'Brush, brambles, and goblin teeth all bounce off.',
  },
  {
    id: 'iron_greaves',
    name: 'Iron greaves',
    slot: 'legs',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 12 },
    armor: 4,
    affixPool: PLATE_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'smithing',
      levelReq: 16,
      xp: 140,
      station: 'anvil',
      ticks: 70,
      inputs: [{ item: 'iron_bar', qty: 2 }],
    },
    value: 280,
    color: '#8d9299',
    code: 'Ig',
    desc: 'Shin-plates that turn a low sweep into a loud noise.',
  },
  {
    id: 'steel_greaves',
    name: 'Steel greaves',
    slot: 'legs',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 31 },
    armor: 7,
    affixPool: [...PLATE_POOL, { stat: 'construction' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'smithing',
      levelReq: 33,
      xp: 260,
      station: 'anvil',
      ticks: 85,
      inputs: [{ item: 'steel_bar', qty: 2 }],
    },
    value: 620,
    color: '#b8bec8',
    code: 'Sg',
    desc: 'Bright steel legs that stride through the front line.',
  },

  // ------------------------------------------------ boots
  {
    id: 'swiftstep_boots',
    name: 'Swiftstep boots',
    slot: 'boots',
    armorClass: 'cloth',
    levelReq: { skill: 'magic', level: 10 },
    armor: 1,
    affixPool: [{ stat: 'magic', w: 2 }, { stat: 'sneak' }, { stat: 'regen' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 12,
      xp: 80,
      station: 'workbench',
      ticks: 50,
      inputs: [{ item: 'cloth', qty: 2 }],
    },
    value: 140,
    color: '#7fc9b3',
    code: 'Sb',
    desc: 'They touch the ground mostly out of politeness.',
  },
  {
    id: 'leather_boots',
    name: 'Leather boots',
    slot: 'boots',
    armorClass: 'leather',
    armor: 2,
    affixPool: LEATHER_POOL,
    acquisition: { craft: true, shop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 2,
      xp: 25,
      station: 'workbench',
      ticks: 35,
      inputs: [{ item: 'leather', qty: 1 }],
    },
    value: 45,
    color: '#6b4a26',
    code: 'Lb',
    desc: 'Every long story starts with a good pair of boots.',
  },
  {
    id: 'wanderer_boots',
    name: "Wanderer's boots",
    slot: 'boots',
    armorClass: 'leather',
    levelReq: { skill: 'archery', level: 14 },
    armor: 2,
    affixPool: [...LEATHER_POOL, { stat: 'fishing' }],
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'crafting',
      levelReq: 18,
      xp: 150,
      station: 'workbench',
      ticks: 65,
      inputs: [
        { item: 'leather', qty: 2 },
        { item: 'wolf_fur', qty: 1 },
      ],
    },
    value: 240,
    color: '#8a6a45',
    code: 'Wb',
    desc: 'Tall, folded, and already broken in by somebody braver.',
  },
  {
    id: 'iron_sabatons',
    name: 'Iron sabatons',
    slot: 'boots',
    armorClass: 'plate',
    levelReq: { skill: 'defence', level: 14 },
    armor: 3,
    affixPool: PLATE_POOL,
    acquisition: { craft: true, drop: true },
    recipe: {
      skill: 'smithing',
      levelReq: 17,
      xp: 145,
      station: 'anvil',
      ticks: 70,
      inputs: [{ item: 'iron_bar', qty: 2 }],
    },
    value: 260,
    color: '#8d9299',
    code: 'Is',
    desc: 'Steel toes settle a surprising number of arguments.',
  },

  // ------------------------------------------------ offhand
  {
    id: 'oak_kiteshield',
    name: 'Oak kiteshield',
    slot: 'offhand',
    levelReq: { skill: 'defence', level: 6 },
    armor: 3,
    affixPool: [{ stat: 'defence', w: 2 }, { stat: 'vitality' }, { stat: 'maxHp' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 9,
      xp: 85,
      station: 'workbench',
      ticks: 60,
      inputs: [
        { item: 'oak_log', qty: 2 },
        { item: 'bronze_bar', qty: 1 },
      ],
    },
    value: 120,
    color: '#6b4a26',
    code: 'Ks',
    desc: 'A tall oak face with a chevron of hammered bronze.',
  },
  {
    id: 'arcane_orb',
    name: 'Arcane orb',
    slot: 'offhand',
    levelReq: { skill: 'magic', level: 16 },
    armor: 0,
    affixPool: [{ stat: 'magic', w: 3 }, { stat: 'vitality' }, { stat: 'regen' }],
    acquisition: { craft: true },
    recipe: {
      skill: 'crafting',
      levelReq: 24,
      xp: 200,
      station: 'workbench',
      ticks: 75,
      inputs: [
        { item: 'gold_bar', qty: 1 },
        { item: 'moonbell', qty: 2 },
      ],
    },
    value: 330,
    color: '#8f9ed6',
    code: 'Ao',
    desc: 'It orbits your palm and hums when you have a good idea.',
  },
];

/** Compiled once at module load — throws loudly on any malformed def. */
export const COMPILED_EQUIPMENT = compileEquipment(EQUIPMENT_DEFS);
