/**
 * THE READING SHEET — emits docs/voice-script.md, the one document a
 * human (or the Chatterbox lane) reads every spoken line of Arx from.
 *
 * Regenerate after any dialogue/actor/quip change:
 *   npx tsx tools/voice/sheet.mts
 *
 * The sheet is generated — edit the sources (dialogue defs, actor
 * defs, tools/voice/quips.json, tools/voice/characters.json), never
 * the sheet itself.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  buildManifest,
  orderedActors,
  REGION_ORDER,
  REPO,
  type Manifest,
  type ManifestLine,
} from './lib.mts';

/** One title per REGION_ORDER row. A region with no title falls back to its id. */
const REGION_TITLES: Record<string, string> = {
  dawnmead: 'Dawnmead — the waking village',
  roads: 'The roads — waystations, watch and the Tollhouse',
  amberford: 'Amberford — the ford town',
  silverfall: 'Silverfall — the capital',
  undercroft: 'The Undercroft — below the mountain',
  pinewatch: 'Pinewatch — the mountain cradle past Hoargate',
  saltmere: 'Saltmere — the harbour and the salt pans',
  hartfell: 'Hartfell — the town past the treeline',
  lowhall: 'The Low Hall — the Red Company below',
};

const SLOT_NOTES: Record<string, string> = {
  greet: 'plays as a conversation opens; the vocal hello under the first written line',
  ack: 'a between-beats acknowledgement, rationed so it stays rare',
  yes: 'an assent beat: the writer marked this moment a yes',
  no: 'a refusal beat',
  hm: 'a considering beat',
  farewell: 'plays as the last line lands',
  bark: 'filler breath for passing one-liners with no recorded line of their own',
};

function esc(s: string): string {
  return s.replace(/\n/g, ' ');
}

function quipBlock(out: string[], lines: ManifestLine[]): void {
  const quips = lines.filter((l) => l.kind === 'quip');
  if (quips.length === 0) return;
  out.push('### Quips — short fillers, one file each');
  out.push('');
  let lastSlot = '';
  for (const q of quips) {
    if (q.slot !== lastSlot) {
      if (lastSlot !== '') out.push('');
      lastSlot = q.slot!;
      out.push(`*${q.slot} — ${SLOT_NOTES[q.slot!]}*`);
      out.push('');
    }
    out.push(`- \`${q.clipId}\` — "${esc(q.text)}"`);
  }
  out.push('');
}

function barkBlock(out: string[], lines: ManifestLine[]): void {
  const barks = lines.filter((l) => l.kind === 'bark');
  if (barks.length === 0) return;
  out.push('### Ambient barks — said in passing; the game matches your recording to the shown line, so record VERBATIM');
  out.push('');
  for (const b of barks) {
    out.push(`- \`${b.clipId}\` — "${esc(b.text)}"`);
  }
  out.push('');
}

function dialogueBlocks(out: string[], m: Manifest, lines: ManifestLine[]): void {
  const nodes = lines.filter((l) => l.kind === 'node');
  if (nodes.length === 0) return;
  const byDialogue = new Map<string, ManifestLine[]>();
  for (const n of nodes) {
    const arr = byDialogue.get(n.dialogue!) ?? [];
    arr.push(n);
    byDialogue.set(n.dialogue!, arr);
  }
  for (const [dlgId, dlgLines] of byDialogue) {
    const def = m.dialogues.find((d) => d.id === dlgId)!;
    const req = def.requires?.length ? ` *(plays when: ${def.requires.join(', ')})*` : '';
    out.push(`### Conversation: \`${dlgId}\`${req}`);
    out.push('');
    for (const n of dlgLines) {
      const cues = (n.context ?? []).join('; or ');
      const mood = n.mood ? ` · mood: ${n.mood}` : '';
      out.push(`**\`${n.clipId}\`**${mood}${cues ? ` — *${esc(cues)}*` : ''}`);
      out.push('');
      out.push(`> ${esc(n.text)}`);
      out.push('');
    }
  }
}

function actorSection(out: string[], m: Manifest, id: string): void {
  const actor = m.actors.get(id)!;
  const note = m.notes[id];
  const lines = m.byActor.get(id)!;
  const nNode = lines.filter((l) => l.kind === 'node').length;
  const nOther = lines.length - nNode;
  out.push(`## ${actor.name} \`${id}\` — ${nNode} dialogue lines, ${nOther} quips and barks`);
  out.push('');
  if (actor.examine) out.push(`*${actor.examine}*`);
  out.push('');
  if (note) {
    out.push(`**Who they are, and how to say it:** ${note.direction}`);
    out.push('');
    const casting =
      note.ttsVoice === null
        ? 'unassigned (the Chatterbox lane skips this character until a voice is set)'
        : `\`${note.ttsVoice}\` *(provisional)*`;
    out.push(
      `**Chatterbox casting:** ${casting} · exaggeration ${note.exaggeration} · cfg ${note.cfgWeight}`,
    );
    out.push('');
  }
  quipBlock(out, lines);
  barkBlock(out, lines);
  dialogueBlocks(out, m, lines);
  out.push('---');
  out.push('');
}

const m = buildManifest();
const ordered = orderedActors(m);
const firstWave = ordered.filter((id) => m.notes[id]?.firstWave);
const rest = ordered.filter((id) => !m.notes[id]?.firstWave);

const out: string[] = [];
out.push('# ARX VOICE SCRIPT — every spoken line in the Dawnlands');
out.push('');
out.push('*Generated by `npx tsx tools/voice/sheet.mts` — edit the dialogue defs,');
out.push('actor defs, `tools/voice/quips.json` or `tools/voice/characters.json`,');
out.push('never this file.*');
out.push('');
const totals = {
  actors: ordered.length,
  node: m.lines.filter((l) => l.kind === 'node').length,
  bark: m.lines.filter((l) => l.kind === 'bark').length,
  quip: m.lines.filter((l) => l.kind === 'quip').length,
};
out.push(
  `**${totals.actors} characters · ${totals.node} dialogue lines · ${totals.bark} ambient barks · ${totals.quip} quips.**`,
);
out.push('');
out.push('## How to record');
out.push('');
out.push('- One file per line. Name it EXACTLY the backticked slug, e.g. `fen_bench__hub.wav`.');
out.push('- Drop finished takes in `voicework/recorded/<character_id>/` in the game repo.');
out.push('  WAV or OGG, mono, 48 kHz or 44.1 kHz, quiet room, no music bed. A human take');
out.push('  always beats a generated one: the importer prefers `recorded/` over `generated/`.');
out.push('- Read the character direction first, then the line. The blockquote is the exact');
out.push('  transcript: say every word, no more, no fewer. `...` is a held pause, not a skip.');
out.push('- Barks must be VERBATIM — the game matches the audio to the displayed line by its text.');
out.push('- Quips are color, not scripts: a grunt slot like `bark` can be half a breath.');
out.push('- To give a character a cloned voice of your own: record 10 to 20 seconds of clean');
out.push('  speech, drop it at `~/code/voicelab/voices/<anything>.wav`, and set that name as');
out.push('  `ttsVoice` in `tools/voice/characters.json`.');
out.push('');
out.push('## The pipeline');
out.push('');
out.push('```');
out.push('npx tsx tools/voice/sheet.mts                  regenerate this sheet');
out.push('npx tsx tools/voice/generate.mts [actor...]    Chatterbox lane -> voicework/generated/');
out.push('npx tsx tools/voice/import.mts [actor...]      both lanes -> the live voice ledger');
out.push('```');
out.push('');
out.push('---');
out.push('');
out.push('# FIRST WAVE — record these first');
out.push('');
out.push('The starter cast every player meets in their opening hours, plus the');
out.push("ford town's daily faces. Quips are authored for all twelve.");
out.push('');
for (const id of firstWave) actorSection(out, m, id);
let lastRegion = '';
for (const id of rest) {
  const region = m.notes[id]?.where ?? REGION_ORDER[0];
  if (region !== lastRegion) {
    lastRegion = region!;
    out.push(`# ${REGION_TITLES[region!] ?? region}`);
    out.push('');
  }
  actorSection(out, m, id);
}

const dest = join(REPO, 'docs/voice-script.md');
writeFileSync(dest, out.join('\n'));
console.log(
  `wrote ${dest}: ${totals.actors} characters, ${totals.node + totals.bark + totals.quip} lines`,
);
