/**
 * THE SECOND BREATH — the breath arts of every school.
 * One shelf of the ability catalog (foundations F6.2) — entries moved
 * verbatim from abilities.ts; the hub spreads every shelf into the one
 * registry, so ids and behavior are untouched.
 */
import type { AbilityDef } from '@arx/shared';

export const BREATH_DEFS: AbilityDef[] = [
  // ------------------- THE SECOND BREATH — the archery breath arts
  // THE LONG ROAD's content wave: every ten-art school grows the same
  // ten breath voices onehand and arx already carry, five casted and
  // five channeled, interleaved up the stretched ladder. The wave laws
  // hold: casted arts carry no castFreezeTicks (the wind-up IS the
  // commit); channels never ride a ground_field.
  {
    id: 'kingshot',
    name: 'Kingshot',
    desc: 'Draw until the bow remembers the forest. One shaft, and the whole lane kneels.',
    color: '#7a9a4a',
    code: 'Kg',
    cooldownTicks: 200, // 10 s
    castTicks: 22, // 1.1 s wound, 0.88 s planted
    shape: 'projectile_fan',
    damage: 16,
    range: 18,
    projectiles: 1,
    projectileSpeed: 22,
    pierce: true,
  },
  {
    id: 'stringsong',
    name: 'Stringsong',
    desc: 'Hold the note and the bow sings it. Arrows leave on every beat.',
    color: '#9ab86a',
    code: 'Sn',
    cooldownTicks: 160, // 8 s
    channelTicks: 48, // three beats of the string
    pulseEveryTicks: 16,
    shape: 'projectile_fan',
    damage: 4,
    range: 14,
    projectiles: 1,
    projectileSpeed: 18,
    element: 'storm',
  },
  {
    id: 'hawks_hour',
    name: "Hawk's Hour",
    desc: 'Mark the field the way the hawk does. What stands in it has already lost.',
    color: '#c8a44a',
    code: 'Hh',
    cooldownTicks: 190, // 9.5 s
    castTicks: 22,
    shape: 'ground_aoe',
    damage: 15,
    range: 13,
    radius: 2.0,
    fuseTicks: 14,
  },
  {
    id: 'winterflight',
    name: 'Winterflight',
    desc: 'Loose down one cold line and keep loosing. The wind does the rest.',
    color: '#8ac4e0',
    code: 'Wf',
    cooldownTicks: 170, // 8.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'beam',
    damage: 4,
    range: 9,
    width: 0.6,
    status: { status: 'chill', power: 1, durationTicks: 40 },
  },
  {
    id: 'emberhead',
    name: 'Emberhead',
    desc: 'Two shafts tipped at the campfire. They finish burning where they land.',
    color: '#e08a4a',
    code: 'Ed',
    cooldownTicks: 210, // 10.5 s
    castTicks: 22,
    shape: 'projectile_fan',
    damage: 9,
    range: 15,
    projectiles: 2,
    spreadArc: 0.14,
    projectileSpeed: 17,
    splashRadius: 1.4,
    status: { status: 'burn', power: 1, durationTicks: 60 },
  },
  {
    id: 'skyloom',
    name: 'Skyloom',
    desc: 'Set the shuttle flying and hold it. The thread stitches foe to foe.',
    color: '#6b9a7a',
    code: 'Sy',
    cooldownTicks: 200, // 10 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'chain_zap',
    damage: 4,
    range: 12,
    radius: 3.5,
    chainTargets: 2,
  },
  {
    id: 'gloamshaft',
    name: 'Gloamshaft',
    desc: 'Draw in the last light and loose after it. The dark travels in a straight line.',
    color: '#5a5a78',
    code: 'Gf',
    cooldownTicks: 210, // 10.5 s
    castTicks: 24,
    shape: 'beam',
    damage: 19,
    range: 12,
    width: 0.55,
  },
  {
    id: 'harrier',
    name: 'Harrier',
    desc: 'The wing that circles back. Every pass takes its due twice.',
    color: '#a8946a',
    code: 'Hr',
    cooldownTicks: 220, // 11 s
    channelTicks: 64, // four passes of the wing
    pulseEveryTicks: 16,
    shape: 'projectile_fan',
    damage: 3,
    range: 10,
    projectiles: 1,
    projectileSpeed: 15,
    returns: true,
  },
  {
    id: 'zenith',
    name: 'Zenith',
    desc: 'Loose at the highest point of the sky. It comes down as noon.',
    color: '#e8c874',
    code: 'Zn',
    cooldownTicks: 230, // 11.5 s
    castTicks: 26,
    shape: 'ground_aoe',
    damage: 16,
    range: 15,
    radius: 2.2,
    fuseTicks: 12,
    status: { status: 'burn', power: 1, durationTicks: 60 },
  },
  {
    id: 'crowsong',
    name: 'Crowsong',
    desc: 'Call the dark flock down on a field and keep calling. They are never full.',
    color: '#4a4458',
    code: 'Cw',
    cooldownTicks: 240, // 12 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'ground_aoe',
    damage: 3,
    range: 13,
    radius: 2.2,
    fuseTicks: 10,
    status: { status: 'bleed', power: 1, durationTicks: 40 },
  },

  // --------------------- THE SECOND BREATH — the sneak breath arts
  {
    id: 'opened_vein',
    name: 'Opened Vein',
    desc: 'The breath before the artery. Let it out slow and it never stops.',
    color: '#9a3040',
    code: 'Vn',
    cooldownTicks: 220, // 11 s
    castTicks: 18,
    shape: 'melee_arc',
    damage: 9,
    range: 2.0,
    arc: 0.9,
    status: { status: 'bleed', power: 2, durationTicks: 100 },
  },
  {
    id: 'threadwork',
    name: 'Threadwork',
    desc: 'Hold still and sew. The needle passes through the same place three times.',
    color: '#7a6a8a',
    code: 'Tk',
    cooldownTicks: 190, // 9.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 4,
    range: 2.0,
    arc: 0.8,
    status: { status: 'bleed', power: 1, durationTicks: 40 },
  },
  {
    id: 'nightshade_kiss',
    name: 'Nightshade Kiss',
    desc: 'A dart steeped a week in the garden nobody plants twice. One kiss is plenty.',
    color: '#8aa050',
    code: 'Nk',
    cooldownTicks: 230, // 11.5 s
    castTicks: 20,
    shape: 'projectile_fan',
    damage: 8,
    range: 9,
    projectiles: 1,
    projectileSpeed: 16,
    status: { status: 'venom', power: 1, durationTicks: 80 },
  },
  {
    id: 'quiet_knife',
    name: 'The Quiet Knife',
    desc: 'A line of hush laid down the corridor. Everything on it opens.',
    color: '#6a6480',
    code: 'Qk',
    cooldownTicks: 180, // 9 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'beam',
    damage: 4,
    range: 7,
    width: 0.5,
    status: { status: 'bleed', power: 1, durationTicks: 40 },
  },
  {
    id: 'redwork',
    name: 'Redwork',
    desc: 'The slow inhale, then the room blooms red around you. Craftwork, of a kind.',
    color: '#a84048',
    code: 'Rd',
    cooldownTicks: 220, // 11 s
    castTicks: 22,
    shape: 'nova',
    damage: 10,
    radius: 2.3,
    status: { status: 'bleed', power: 1, durationTicks: 60 },
  },
  {
    id: 'gallows_thread',
    name: 'Gallows Thread',
    desc: 'The noose passes down the line, one neck at a time. Hold the knot.',
    color: '#5a5468',
    code: 'Gh',
    cooldownTicks: 220, // 11 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'chain_zap',
    damage: 4,
    range: 9,
    radius: 3.0,
    chainTargets: 2,
    status: { status: 'venom', power: 1, durationTicks: 40 },
  },
  {
    id: 'widows_draw',
    name: "Widow's Draw",
    desc: 'A fan of steeped needles, dealt like cards. Everyone at the table loses.',
    color: '#b0b47a',
    code: 'Wd',
    cooldownTicks: 230, // 11.5 s
    castTicks: 22,
    shape: 'projectile_fan',
    damage: 7,
    range: 10,
    projectiles: 3,
    spreadArc: 0.5,
    projectileSpeed: 15,
    element: 'verdant',
    status: { status: 'venom', power: 1, durationTicks: 60 },
  },
  {
    id: 'bloodletting',
    name: 'Bloodletting',
    desc: 'The old surgery, held to its rhythm. What they lose is yours to keep.',
    color: '#8a2a34',
    code: 'Bt',
    cooldownTicks: 220, // 11 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 4,
    range: 2.1,
    arc: 1.0,
    drainFrac: 0.15,
    status: { status: 'bleed', power: 1, durationTicks: 40 },
  },
  {
    id: 'lights_out',
    name: 'Lights Out',
    desc: 'Pinch the wick of a whole room. The dark arrives before the knife does.',
    color: '#3a3450',
    code: 'Lx',
    cooldownTicks: 220, // 11 s
    castTicks: 24,
    shape: 'ground_aoe',
    damage: 14,
    range: 10,
    radius: 2.0,
    fuseTicks: 10,
    status: { status: 'chill', power: 1, durationTicks: 50 },
  },
  {
    id: 'red_hour',
    name: 'The Red Hour',
    desc: 'The hour where every second cuts. Stand in the middle of it and count.',
    color: '#c4384a',
    code: 'Rh',
    cooldownTicks: 260, // 13 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'nova',
    damage: 4,
    radius: 2.0,
    status: { status: 'bleed', power: 1, durationTicks: 40 },
  },

  // -------------------- THE SECOND BREATH — the shield breath arts
  {
    id: 'iron_toll',
    name: 'Iron Toll',
    desc: 'Strike the boss and the shield rings like a bell. The toll is paid outward.',
    color: '#8ea4b8',
    code: 'Il',
    cooldownTicks: 190, // 9.5 s
    castTicks: 20,
    shape: 'nova',
    damage: 9,
    radius: 2.2,
    knockback: 1.2,
    status: { status: 'shock', power: 1, durationTicks: 30 },
  },
  {
    id: 'grindstone',
    name: 'Grindstone',
    desc: 'Set the rim against them and turn. Armor comes off in curls.',
    color: '#9a9484',
    code: 'Gn',
    cooldownTicks: 200, // 10 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 4,
    range: 2.0,
    arc: 1.2,
    status: { status: 'sunder', power: 10, durationTicks: 60 },
  },
  {
    id: 'doorfall',
    name: 'Doorfall',
    desc: 'Lift the wall and lay it down on them. Doors open both ways.',
    color: '#7d8a9a',
    code: 'Do',
    cooldownTicks: 210, // 10.5 s
    castTicks: 22,
    shape: 'ground_aoe',
    damage: 12,
    range: 4,
    radius: 2.0,
    fuseTicks: 8,
    knockback: 1.4,
  },
  {
    id: 'held_gate',
    name: 'Held Gate',
    desc: 'Brace, and hold the cold line of the lane. Nothing crosses while you breathe.',
    color: '#7ab0cc',
    code: 'Hg',
    cooldownTicks: 190, // 9.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'beam',
    damage: 4,
    range: 6,
    width: 0.7,
    status: { status: 'chill', power: 1, durationTicks: 40 },
  },
  {
    id: 'sunbrass',
    name: 'Sunbrass',
    desc: 'Catch noon on the boss and turn it loose. Brass remembers the sun.',
    color: '#d9b45e',
    code: 'Sb',
    cooldownTicks: 230, // 11.5 s
    castTicks: 24,
    shape: 'nova',
    damage: 10,
    radius: 2.6,
    knockback: 1.0,
    status: { status: 'burn', power: 1, durationTicks: 50 },
  },
  {
    id: 'millwall',
    name: 'Millwall',
    desc: 'The wall turns like a mill wheel. Every turn throws the water back.',
    color: '#8a94a4',
    code: 'Mw',
    cooldownTicks: 250, // 12.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'nova',
    damage: 4,
    radius: 2.1,
    knockback: 0.8,
  },
  {
    id: 'anchorfall',
    name: 'Anchorfall',
    desc: 'Be the anchor. The sea parts where you land and stays parted.',
    color: '#6a94b0',
    code: 'Ac',
    cooldownTicks: 250, // 12.5 s
    castTicks: 22,
    shape: 'leap_slam',
    damage: 12,
    dashTiles: 8,
    radius: 2.2,
    knockback: 1.6,
    status: { status: 'chill', power: 1, durationTicks: 50 },
  },
  {
    id: 'patient_wall',
    name: 'The Patient Wall',
    desc: 'The wall advances one strike at a time. It has nowhere else to be.',
    color: '#a4988a',
    code: 'Pl',
    cooldownTicks: 230, // 11.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 4,
    range: 2.2,
    arc: 1.4,
    knockback: 0.5,
  },
  {
    id: 'standing_sun',
    name: 'The Standing Sun',
    desc: 'Plant the light like a standard. Where it stands, the day holds.',
    color: '#e8cc84',
    code: 'Su',
    cooldownTicks: 240, // 12 s
    castTicks: 26,
    shape: 'ground_aoe',
    damage: 14,
    range: 5,
    radius: 2.4,
    fuseTicks: 10,
    knockback: 1.2,
    status: { status: 'burn', power: 1, durationTicks: 60 },
  },
  {
    id: 'winterhold',
    name: 'Winterhold',
    desc: 'The cold keep, held from behind the boss. The court freezes outward.',
    color: '#a0c8dc',
    code: 'Wt',
    cooldownTicks: 270, // 13.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'nova',
    damage: 4,
    radius: 2.3,
    status: { status: 'chill', power: 1, durationTicks: 60 },
  },

  // ------------------- THE SECOND BREATH — the twohand breath arts
  {
    id: 'fell_timber',
    name: 'Fell Timber',
    desc: 'The tree comes down where you say it does. Stand clear or be counted.',
    color: '#8a7a4e',
    code: 'Fe',
    cooldownTicks: 190, // 9.5 s
    castTicks: 20,
    shape: 'melee_arc',
    damage: 12,
    range: 2.7,
    arc: 1.3,
    knockback: 1.5,
  },
  {
    id: 'quarry_work',
    name: 'Quarry Work',
    desc: 'Swing after swing into the same seam. Every stone splits eventually.',
    color: '#9a8a78',
    code: 'Qy',
    cooldownTicks: 210, // 10.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 5,
    range: 2.5,
    arc: 1.7,
    status: { status: 'sunder', power: 10, durationTicks: 60 },
  },
  {
    id: 'forgefall',
    name: 'Forgefall',
    desc: 'The hammer leaves the forge still glowing. It lands like a verdict.',
    color: '#d97a3d',
    code: 'Fo',
    cooldownTicks: 250, // 12.5 s
    castTicks: 22,
    shape: 'leap_slam',
    damage: 13,
    dashTiles: 9.0,
    radius: 2.2,
    knockback: 1.5,
    status: { status: 'burn', power: 1, durationTicks: 50 },
  },
  {
    id: 'wheelbreaker',
    name: 'The Wheelbreaker',
    desc: 'Drive the haft down the lane like a ram. Wheels were a mistake.',
    color: '#b09a6a',
    code: 'Wk',
    cooldownTicks: 200, // 10 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'beam',
    damage: 5,
    range: 7,
    width: 0.8,
    knockback: 0.6,
    status: { status: 'shock', power: 1, durationTicks: 30 },
  },
  {
    id: 'gravedigger',
    name: 'Gravedigger',
    desc: 'Open the ground and it wants filling. Everything nearby obliges.',
    color: '#6a5e6e',
    code: 'Gv',
    cooldownTicks: 240, // 12 s
    castTicks: 24,
    shape: 'ground_aoe',
    damage: 15,
    range: 4.5,
    radius: 2.1,
    fuseTicks: 10,
    knockback: -1.0, // the grave PULLS
  },
  {
    id: 'ore_song',
    name: 'Ore Song',
    desc: 'The maul sings against the seam and the seam sings back. Keep time.',
    color: '#b8a488',
    code: 'Oe',
    cooldownTicks: 260, // 13 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'nova',
    damage: 5,
    radius: 2.4,
    knockback: 0.7,
  },
  {
    id: 'skyweight',
    name: 'Skyweight',
    desc: 'Lift the whole sky as high as it goes. Then let it remember the ground.',
    color: '#c9a24a',
    code: 'Sw',
    cooldownTicks: 250, // 12.5 s
    castTicks: 24,
    shape: 'pulse_nova',
    damage: 9,
    radius: 2.4,
    pulses: 2,
    pulseEveryTicks: 11,
    knockback: 1.4,
  },
  {
    id: 'long_lever',
    name: 'The Long Lever',
    desc: 'Given a place to stand, you move them. The lever is the whole lane.',
    color: '#a08a68',
    code: 'Lv',
    cooldownTicks: 230, // 11.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'beam',
    damage: 4,
    range: 8,
    width: 0.7,
    knockback: 0.5,
  },
  {
    id: 'sunhammer',
    name: 'Sunhammer',
    desc: 'Swing the noon itself. Everything it touches keeps a little of the heat.',
    color: '#e0a04c',
    code: 'Sm',
    cooldownTicks: 240, // 12 s
    castTicks: 26,
    shape: 'melee_arc',
    damage: 15,
    range: 2.8,
    arc: 1.6,
    knockback: 1.3,
    status: { status: 'burn', power: 1, durationTicks: 60 },
  },
  {
    id: 'worlds_rim',
    name: "World's Rim",
    desc: 'Grind the far edge of the world against a chosen field. It turns slowly.',
    color: '#8a9aa8',
    code: 'Wm',
    cooldownTicks: 260, // 13 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'ground_aoe',
    damage: 4,
    range: 5,
    radius: 2.3,
    fuseTicks: 8,
    status: { status: 'chill', power: 1, durationTicks: 50 },
  },

  // ----------------- THE SECOND BREATH — the dualwield breath arts
  {
    id: 'two_bells',
    name: 'Two Bells',
    desc: 'Both edges ring at once. The pair of them is the whole carillon.',
    color: '#d9c46a',
    code: '2b',
    cooldownTicks: 160, // 8 s
    castTicks: 18,
    shape: 'melee_arc',
    damage: 10,
    range: 2.2,
    arc: 1.0,
    status: { status: 'shock', power: 1, durationTicks: 30 },
  },
  {
    id: 'ribbonwork',
    name: 'Ribbonwork',
    desc: 'The ribbons cross, and cross, and cross. Red suits everyone.',
    color: '#c45a4a',
    code: 'Rb',
    cooldownTicks: 210, // 10.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 5,
    range: 2.1,
    arc: 1.1,
    status: { status: 'bleed', power: 1, durationTicks: 40 },
  },
  {
    id: 'twin_moons',
    name: 'Twin Moons',
    desc: 'Both blades loosed on the same orbit. They always come home.',
    color: '#b8c4d8',
    code: 'Tn',
    cooldownTicks: 200, // 10 s
    castTicks: 20,
    shape: 'projectile_fan',
    damage: 6,
    range: 9,
    projectiles: 2,
    spreadArc: 0.18,
    projectileSpeed: 16,
    returns: true,
  },
  {
    id: 'silver_reel',
    name: 'Silver Reel',
    desc: 'Spin the pair into one cold circle. The reel winds everything in reach.',
    color: '#a8c0cc',
    code: 'Sr',
    cooldownTicks: 230, // 11.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'nova',
    damage: 5,
    radius: 1.9,
    status: { status: 'chill', power: 1, durationTicks: 40 },
  },
  {
    id: 'matched_flame',
    name: 'Matched Flame',
    desc: 'Two wicks, one held breath. The burst of strikes lands already burning.',
    color: '#e0854a',
    code: 'Mf',
    cooldownTicks: 220, // 11 s
    castTicks: 22,
    shape: 'flurry',
    damage: 6,
    range: 2.1,
    arc: 1.1,
    hits: 3,
    pulseEveryTicks: 6,
    status: { status: 'burn', power: 1, durationTicks: 40 },
  },
  {
    id: 'stormstitch',
    name: 'Stormstitch',
    desc: 'The left hand throws and the right answers. The seam runs foe to foe.',
    color: '#c8c86a',
    code: 'Sh',
    cooldownTicks: 220, // 11 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'chain_zap',
    damage: 5,
    range: 8,
    radius: 3.0,
    chainTargets: 2,
    status: { status: 'shock', power: 1, durationTicks: 30 },
  },
  {
    id: 'mirrorfall',
    name: 'Mirrorfall',
    desc: 'You and your reflection land together. Only one of you is survivable.',
    color: '#9ab8c8',
    code: 'Mi',
    cooldownTicks: 220, // 11 s
    castTicks: 20,
    shape: 'leap_slam',
    damage: 12,
    dashTiles: 8,
    radius: 1.9,
    status: { status: 'chill', power: 1, durationTicks: 40 },
  },
  {
    id: 'the_weave',
    name: 'The Weave',
    desc: 'Warp and weft, held to the count. Every thread crosses the loom.',
    color: '#b0a4c0',
    code: 'Wv',
    cooldownTicks: 200, // 10 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 5,
    range: 2.2,
    arc: 1.3,
  },
  {
    id: 'first_and_last',
    name: 'First and Last',
    desc: 'The first cut opens the door. The last one closes it behind them.',
    color: '#e8d8a0',
    code: 'Fx',
    cooldownTicks: 190, // 9.5 s
    castTicks: 24,
    shape: 'melee_arc',
    damage: 12,
    range: 2.3,
    arc: 1.0,
    executeBelow: { frac: 0.3, mult: 2.0 },
  },
  {
    id: 'hummingbird',
    name: 'Hummingbird',
    desc: 'Wings too fast to see, held on one flower. Count the visits if you can.',
    color: '#8ac4a8',
    code: 'Hm',
    cooldownTicks: 240, // 12 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'projectile_fan',
    damage: 3,
    range: 9,
    projectiles: 2,
    spreadArc: 0.16,
    projectileSpeed: 17,
  },

  // ------------------- THE SECOND BREATH — the combat breath arts
  {
    id: 'measured_blow',
    name: 'Measured Blow',
    desc: 'The breath before the fist. Measured twice, landed once.',
    color: '#b09a7a',
    code: 'Me',
    cooldownTicks: 170, // 8.5 s
    castTicks: 18,
    shape: 'melee_arc',
    damage: 11,
    range: 2.3,
    arc: 1.0,
  },
  {
    id: 'drumbeat',
    name: 'Drumbeat',
    desc: 'The old cadence, kept with your heels. The whole line moves to it.',
    color: '#c4885a',
    code: 'Dm',
    cooldownTicks: 240, // 12 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'nova',
    damage: 5,
    radius: 2.0,
    knockback: 0.6,
  },
  {
    id: 'thrown_iron',
    name: 'Thrown Iron',
    desc: 'Whatever iron is near, thrown hard enough to matter. Everything is a weapon.',
    color: '#8a8f98',
    code: 'Th',
    cooldownTicks: 180, // 9 s
    castTicks: 20,
    shape: 'projectile_fan',
    damage: 12,
    range: 9,
    projectiles: 1,
    projectileSpeed: 14,
    splashRadius: 1.3,
  },
  {
    id: 'ironbreath',
    name: 'Ironbreath',
    desc: 'The veteran exhales winter down the lane. Cold as pay day, twice as slow.',
    color: '#9ab4bc',
    code: 'Ih',
    cooldownTicks: 210, // 10.5 s
    channelTicks: 48,
    pulseEveryTicks: 16,
    shape: 'beam',
    damage: 5,
    range: 6,
    width: 0.6,
    status: { status: 'chill', power: 1, durationTicks: 40 },
  },
  {
    id: 'fifth_road',
    name: 'The Fifth Road',
    desc: 'Four roads are taught. The fifth goes through whoever is standing on it.',
    color: '#7a6a80',
    code: '5r',
    cooldownTicks: 220, // 11 s
    castTicks: 22,
    shape: 'dash_strike',
    damage: 12,
    dashTiles: 9.0,
    travel: 'charge',
    status: { status: 'bleed', power: 1, durationTicks: 50 },
  },
  {
    id: 'old_thunder',
    name: 'Old Thunder',
    desc: 'The joints remember every storm they marched through. Let them speak.',
    color: '#b8a45a',
    code: 'Od',
    cooldownTicks: 210, // 10.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'melee_arc',
    damage: 4,
    range: 2.3,
    arc: 1.2,
    status: { status: 'shock', power: 1, durationTicks: 25 },
  },
  {
    id: 'gathered_breath',
    name: 'The Gathered Breath',
    desc: 'All of it, held as long as it keeps. Then all of it, at once.',
    color: '#d9c084',
    code: 'Gg',
    cooldownTicks: 210, // 10.5 s
    castTicks: 24,
    shape: 'nova',
    damage: 12,
    radius: 2.5,
    knockback: 1.0,
  },
  {
    id: 'long_watch',
    name: 'The Long Watch',
    desc: 'You know where they will stand before they do. The watch never lifted.',
    color: '#7a8a94',
    code: 'Lh',
    cooldownTicks: 250, // 12.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'ground_aoe',
    damage: 4,
    range: 6,
    radius: 2.1,
    fuseTicks: 8,
  },
  {
    id: 'scarworn',
    name: 'Scarworn',
    desc: 'Every scar is a paid receipt. This is where you collect.',
    color: '#a05a48',
    code: 'Sx',
    cooldownTicks: 200, // 10 s
    castTicks: 24,
    shape: 'melee_arc',
    damage: 13,
    range: 2.4,
    arc: 1.2,
    drainFrac: 0.2,
  },
  {
    id: 'last_lesson',
    name: 'Last Lesson',
    desc: 'The lesson passes from one student to the next. Nobody graduates.',
    color: '#c9b46a',
    code: 'Ln',
    cooldownTicks: 250, // 12.5 s
    channelTicks: 64,
    pulseEveryTicks: 16,
    shape: 'chain_zap',
    damage: 4,
    range: 7,
    radius: 3.0,
    chainTargets: 2,
  },
];
